
services:
  db:
    container_name: IUseArchBTW-db
    image: mysql # shold take the latest image
    # port 3306 is the default mysql port
    # use it for debugging only
    ports:
      - "3306:3306"
    networks:
      - internal
    hostname: db
    environment:
      MYSQL_DATABASE: arch
      MYSQL_ROOT_PASSWORD: arch
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d:z

    
  spring-app:
    container_name: IUseArchBTW-api
    build: 
      dockerfile: ./Dockerfile
    pull_policy: build
    ports:
      - "8080:8080"
    depends_on:
      - db
    develop:
      watch:
        - path: ./app 
          action: rebuild
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: arch
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: arch
    networks:
      - internal
volumes: 
  db_data:


networks:
  internal: # we sh
